name: Deploy Github Pages
on:
  release: 
    types:
    - released
    branches: 
    - "root"
jobs:
  deploy:
    name: Deploy Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1 
        with:
          dotnet-version: '7.0.x' # SDK Version to use

      - name: Change base-tag
        run: sed -i 's/<base href="\/" \/>/<base href="\/Qkmaxware.Vm\/" \/>/g' Qkmaxware.Vm.Web/wwwroot/index.html

      - name: Build Site
        env: 
          GITHUB_USERNAME: qkmaxware
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet publish Qkmaxware.Vm.Web -c Release -o .site

      - name: Add .nojekyll file
        run: touch .site/wwwroot/.nojekyll

      - name: Custom 404
        run: cp .site/wwwroot/index.html .site/wwwroot/404.html

      - name: Commit to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        permissions:
          contents: write
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .site/wwwroot